---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-init-config
  namespace: default
  labels:
    k8s-app: filebeat-init
data:
  filebeat.yml: |-
    setup.template.settings:
      index.mapping.total_fields.limit: 10000
    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: filebeat-init
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: filebeat-init
        image: docker.elastic.co/beats/filebeat:7.12.0
        args: [
          "-c", "/etc/filebeat.yml",
          "--modules", "system",
          "-e",
          "setup"
        ]
        env:
        - name: ELASTIC_CLOUD_ID
          valueFrom:
            secretKeyRef:
              name: cloud-secret
              key: cloud-id
        - name: ELASTIC_CLOUD_AUTH
          valueFrom:
            secretKeyRef:
              name: cloud-secret
              key: cloud-auth
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-init-config
      restartPolicy: Never
  backoffLimit: 0